### ISSUE TITLE
dobuild fails with sed error

### ISSUE THREAD

**Issue by 5dma** [eyalroz/bidimailui#133]
Hello! I've been using bidimailui for quite some time, and it has been really reliable.
With a new computer, I'm trying to build the extension by running `dobuild`.

```
$ ./dobuild -v 128 -b release
sed: can't read package.json.in: No such file or directory
```
The error seems to be in [line 122](https://github.com/eyalroz/bidimailui/blob/master/dobuild#L122), where sed is expecting a file `package.json.in` that is not provided in the repo.

Can you fix, or how can I fix?

Thank you.

**Comment by eyalroz** [comment]
You are absolutely right, introduced this retroactively into e7dcf9e86e0a6f58ca3f80cde95ed4ae2ce2f458

**Comment by eyalroz** [comment]
Please try pulling and building again to make sure we're ok now.

**Comment by 5dma** [comment]
Thank you very much. I ran the build job in the `development` branch, added the extension to Thunderbird, and everything is working as expected. (Maybe you want to merge the `development` branch into `master`?)

![bidi](https://github.com/user-attachments/assets/f8c1b02b-f819-421b-999d-6e14db2b6f03)
