### ISSUE TITLE
XML Parsing Error: prefix not bound to a namespace when you click add-on preferences

### ISSUE THREAD

**Issue by KIAOman2020** [eyalroz/bidimailui#27]
Hi @eyalroz,

Thank you for your efforts maintaining BiDi add-on. I'm trying to change default text encoding through add-on preferences but I'm getting below error message:

XML Parsing Error: prefix not bound to a namespace
Location: chrome://bidimailpack/content/bidimailpack-prefs-68.xul
Line Number 59, Column 7:      <html:input id="space_between_paragraphs_value_text"
------^

BiDimailui version: 0.10.1b2
TB version: 68.10.0 under Ubuntu 18.04

**Comment by eyalroz** [comment]
Have you tried [0.10.1](https://github.com/eyalroz/bidimailui/releases/tag/v0.10.1)? I fixed that issue since 0.10.1b2

**Comment by KIAOman2020** [comment]
Thanks @eyalroz , I did update to version 0.10.1 and issue resolved. However version 0.10.1.1 shows its not compatible with TB 68.10!

Yes we are running FOSS Camps,conferences,workshops in Oman since2010!

**Comment by eyalroz** [comment]
Hmm. Weird that 0.10.1.1 shows that. Maybe it's because ATN doesn't recognize it? Anyway, if 0.10.1 works for you, then good enough.
