### ISSUE TITLE
Extension does not support Thunderbird 78

### ISSUE THREAD

**Issue by ocp1000** [eyalroz/bidimailui#3]
Recently released Thunderbird 78.0 has a new compose interface. I believe this is what broke the extension.
There are no RTL buttons when you compose a message.
See attached screenshot.

Machine details:
Windows 10 Pro (Version 2004 19041.388)
Thunderbird 78.0
BiDi UI version: 0.10.1b2

![bidi ui2](https://user-images.githubusercontent.com/44881767/87848742-a6d3f580-c8eb-11ea-97eb-2abe758a1057.png)
![bidi ui](https://user-images.githubusercontent.com/44881767/87848743-a76c8c00-c8eb-11ea-97d2-e90baba736a2.png)

**Comment by eyalroz** [comment]
The extension is not broken - it just doesn't support TB 78, so it's disabled and not loaded.

TB 78 has removed support for regular XUL-based extensions - unfortunately. It will take quite a bit of rewriting work to adapt BiDi Mail UI to TB 78 - and I'm actually not even sure it will be entirely possible, that remains to be seen. I hope to have the time to do that later this month or in August. Until then - sorry.

**Comment by ocp1000** [comment]
1. Thanks for all the hard work; You'll get there, when you'll get there.
2. Any way to make the extension show it's not supported in 78.0? Or it is up to Thunderbird itself to determinate that?
Currently it's displayed as "Enabled".

**Comment by eyalroz** [comment]
1. Thanks :-)
2. It's up to Thunderbird. I actually don't know why it's displayed as "Enabled" - that should not be the case.

**Comment by eyalroz** [comment]
@ocp1000  and others:  Please try [the new beta version 0.11b1](https://github.com/eyalroz/bidimailui/releases/tag/v0.11b1), with Thunderbird 78 support.

Known issue; toolbar buttons go back to the "customize toolbar" dialog when you restart Thunderbird. Please report any other issues.

**Comment by omriossie** [comment]
@eyalroz Amazing! Thanks for the effort. If I'll find any bugs I'll report them.

**Comment by ocp1000** [comment]
@eyalroz Amazing! Works perfectly! If I'll find any issues I'll report them.

**Comment by simchawachtel** [comment]
This is the first time I've compiled an add-on from source code, so maybe I'm doing it wrong. I zipped the src directory and gave the archive the xpi extension. When I tried to install it in Thunderbird, it told me the file was corrupt. I'd be grateful for any hints.

**Comment by simchawachtel** [comment]
I mean, I zipped the CONTENTS of the src directory

**Comment by KIAOman2020** [comment]
> This is the first time I've compiled an add-on from source code, so maybe I'm doing it wrong. I zipped the src directory and gave the archive the xpi extension. When I tried to install it in Thunderbird, it told me the file was corrupt. I'd be grateful for any hints.


Hi @simchawachtel  You need to compile the source file after you unzip it. I have used command " sudo ./dobuild thunderbird " in Ubuntu Linux terminal and I got .xpi file.  Find the file.
[bidimailui_0.11b1_tbird.zip](https://github.com/eyalroz/bidimailui/files/5068933/bidimailui_0.11b1_tbird.zip)

**Comment by KIAOman2020** [comment]
> @eyalroz Amazing! Works perfectly! If I'll find any issues I'll report them.

@eyalroz  works with also, thanks. How I can change default text encoding? previous version I remember it was asking to select default text encoding after installation.

**Comment by simchawachtel** [comment]
> > This is the first time I've compiled an add-on from source code, so maybe I'm doing it wrong. I zipped the src directory and gave the archive the xpi extension. When I tried to install it in Thunderbird, it told me the file was corrupt. I'd be grateful for any hints.
> 
> Hi @simchawachtel You need to compile the source file after you unzip it. I have used command " sudo ./dobuild thunderbird " in Ubuntu Linux terminal and I got .xpi file. Find the file.
> [bidimailui_0.11b1_tbird.zip](https://github.com/eyalroz/bidimailui/files/5068933/bidimailui_0.11b1_tbird.zip)

Thanks. That did the trick for me.

**Comment by eyalroz** [comment]
I want to draw everyone's attention (@simchawachtel , @KIAOman2020 ) to the fact that I make _releases_, and that's what most users should be using.

The latest release is 0.11b2, which you can get from [here](https://github.com/eyalroz/bidimailui/releases/tag/v0.11b2). No need to run `dobuild` yourself.

**Comment by KIAOman2020** [comment]
@eyalroz I didn't find xps file for 0.11b2 under releases page, I can see only source file and I tried to compile and install it, but TB78.1.1 shows its corrupted file.

**Comment by eyalroz** [comment]
@KIAOman2020 : Try it again now please.

**Comment by KIAOman2020** [comment]
@eyalroz I'm getting file corrupted message after I install xps file.

**Comment by eyalroz** [comment]
Ok, so, half of the problem is gone... I've re-uploaded a file, hopefully this one should be valid. Direct link:

https://github.com/eyalroz/bidimailui/releases/download/v0.11b2/bidimailui_0.11b2_tbird.xpi

**Comment by KIAOman2020** [comment]
Thanks @eyalroz , now it's working. However I notice strange behavior with text encoding while viewing email, I will open new issue for it.

**Comment by eyalroz** [comment]
Ok, looking forward to it.
