### ISSUE TITLE
Make the extension compatible with TB 91.* 

### ISSUE THREAD

**Issue by shemeshg** [eyalroz/bidimailui#47]
Installing on recent thunderbird (version 91) produce error.

```
Could not be installed because it is not compatible with thunderbird 91 
```

**Comment by eyalroz** [comment]
@shemeshg : Unfortunately, the extension really does not yet support TB 91. A lot of the functionality is broken with TB 91, so I can't just up the max version. I need to find the time to work on this.

**Comment by shemeshg** [comment]
Seems <ul> aren't RTL correctlly, it produce something like this
```
  <body bidimailui-charset-is-forced="true" style="direction: ltr;">
    <p style="direction: rtl;">שלום עולם</p>
    <ul>
      <li>שלום</li>
      <li><br>
      </li>
    </ul>
  </body>
```
also the <HR> break things , but I think it was a bug in the previous release also
```
<!DOCTYPE html><html style="direction: ltr;">
  <head>

    <meta http-equiv="content-type" content="text/html; charset=">
    <style id="bidiui-paragraph-margins" type="text/css">body p { margin-bottom: 0cm; margin-top: 0pt; } </style>
  </head>
  <body bidimailui-charset-is-forced="true" style="direction: ltr;">
    <p style="direction: rtl;">שלום עולם</p>
    <blockquote>
      <p style="direction: rtl;"><b>שדג</b> 🙁</p>
      <hr width="100%" size="2">שלום<br>
      <br>
    </blockquote>
  </body>
</html>
```

Tables actually works with no problem.

**Comment by eyalroz** [comment]
If this is not related to TB 91 compatibility, please consider deleting your comment and creating a new issue instead.

**Comment by shemeshg** [comment]
It loaded successfully on TB 91

**Comment by thed0ct0r** [comment]
> Please try the new beta:
> 
> https://github.com/eyalroz/bidimailui/releases/tag/v0.12.0b1

i can also confirm this fixed the issues i was having with thunderbird v91.1.0
thanks @eyalroz for this!

**Comment by shemeshg** [comment]
YEs, it indid solved this issue and
also #49
