### ISSUE TITLE
RTL incorrect for H.Line and Numbered list

### ISSUE THREAD

**Issue by shemeshg** [eyalroz/bidimailui#49]
Seems 
```
<ul>
``` 
 aren't RTL'ed  correctly, it produce something like this
```
  <body bidimailui-charset-is-forced="true" style="direction: ltr;">
    <p style="direction: rtl;">שלום עולם</p>
    <ul>
      <li>שלום</li>
      <li><br>
      </li>
    </ul>
  </body>
```
also the 
```
<HR>
``` 

break things , but I think it was a bug in the previous release also
(because it does not produce P object, it just uses BR for new line, 

```
<!DOCTYPE html><html style="direction: ltr;">
  <head>

    <meta http-equiv="content-type" content="text/html; charset=">
    <style id="bidiui-paragraph-margins" type="text/css">body p { margin-bottom: 0cm; margin-top: 0pt; } </style>
  </head>
  <body bidimailui-charset-is-forced="true" style="direction: ltr;">
    <p style="direction: rtl;">שלום עולם</p>
    <blockquote>
      <p style="direction: rtl;"><b>שדג</b> 🙁</p>
      <hr width="100%" size="2">שלום<br>
      <br>
    </blockquote>
  </body>
</html>
```

For comparison - See how in english it keeps using P correcttly
```
<!DOCTYPE html><html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=">
  </head>
  <body>
    <p>shalom</p>
    <hr width="100%" size="2">
    <p>this line is nexct</p>
    <p>sadf</p>
    <p><br>
    </p>
    <p><br>
    </p>
  </body>
</html>
```

Without the addon.
Startting with:
```
<!DOCTYPE html><html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=">
  </head>
  <body>
    <p>shalom</p>
    <p style="direction: rtl;">שלום</p>
    </p>
  </body>
</html>
```
Pressing Enter the H.Line Icon actually worked fine and produced working result
```
<!DOCTYPE html><html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=">
  </head>
  <body>
    <p>shalom</p>
    <p style="direction: rtl;">שלום</p>
    <hr width="100%" size="2">
    <p style="direction: rtl;"><br>
    </p>
  </body>
</html>
```

Tables actually works with no problem.
Beside that it is OK.

**Comment by eyalroz** [comment]
Are we talking about message composition, or display?

If it's display, would you mind attaching a full message (e.g. .eml in a zip file)?

**Comment by shemeshg** [comment]
It is a copy in "Composition" mode from the 
ThunderHTMLedit Addon.

To reproduce the test case:
1. Press the "RTL" icon
2. Type "שלום עולם"
3. Press the H.line Icon.
4. Switch from "Edit" tab to the "HTML" Tab  and analyze result.

The HR causing BR I could not reproduce, but the LI causing BR could be easily reproduce with
1. Start Numbered table, 
2. Set first LI to RTL item
3. Second to LTR
4. Try the 3rd to RTL

![Screen Shot 2021-08-29 at 0 49 02](https://user-images.githubusercontent.com/8200598/131232011-536ed51f-17a5-4646-8b4e-ea19af633431.png)
![Screen Shot 2021-08-29 at 0 50 26](https://user-images.githubusercontent.com/8200598/131232013-2dba0806-7572-482b-972a-b34bc417d7c5.png)
![Screen Shot 2021-08-29 at 0 50 54](https://user-images.githubusercontent.com/8200598/131232014-79ef360e-95d8-4293-a12c-c7cb333a614c.png)
![Screen Shot 2021-08-29 at 0 51 18](https://user-images.githubusercontent.com/8200598/131232015-1a9a0580-fb1f-4bdb-be1f-1348de54970f.png)
![Screen Shot 2021-08-29 at 0 53 17](https://user-images.githubusercontent.com/8200598/131232016-f6d07665-63f0-44cd-8882-0828f3e9fea9.png)

**Comment by shemeshg** [comment]
Confirm, these fix all these issues.

FYI
There are issues with the Core Rendering of thunderbird in RTL mode. but it has nothing to do with this addon.
The Addon now works as expected.

Thanks
Shemeshg
