### ISSUE TITLE
The addon stopped working in 91.1

### ISSUE THREAD

**Issue by DmitryBurstein** [eyalroz/bidimailui#50]
I'm not sure it worked in 91.0, but in 91.1 the toolbar buttons are not there and Ctrl+Shift+R/L is not working either.

**Comment by eyalroz** [comment]
Are you using the latest beta? [0.12b1](https://github.com/eyalroz/bidimailui/releases/tag/v0.12.0b1)?

**Comment by DmitryBurstein** [comment]
No, I was still with the "stable" - 0.11. Just installed your last beta, and it works flawlessly.
Thanks a lot for the link!

**Comment by eyalroz** [comment]
Well, I guess that should be enough positive feedback to upload it to ATN...
