### ISSUE TITLE
The addon does not work on Thunderbird 91.8

### ISSUE THREAD

**Issue by pashazadeh** [eyalroz/bidimailui#54]
I don't know why, but I have installed the plugin on Thunderbird 91.8, and 91.7, but it does not show the direction buttons. I couldn't find any wiki or guidelines, so I posted it here.

**Comment by eyalroz** [comment]
1. Did you try customizing the toolbar?
2. Are you getting any relevant errors in the error console (it's on the Tools menu, under Developer Tools).

**Comment by eyalroz** [comment]
@kleinron Please file that as a separate bug - we don't actually know that this is the same issue.

**Comment by eyalroz** [comment]
Poster, you may reopen if you can answer my questions and reproduce with release 0.13b1.
