### ISSUE TITLE
Toolbar icons don't look good in dark theme

### ISSUE THREAD

**Issue by yoav-steinberg** [eyalroz/bidimailui#56]
Toolbar icons don't look good in dark theme (Ubuntu):

![image](https://user-images.githubusercontent.com/1160578/172555539-f7004704-f941-4fb6-8254-1efe5cc90aef.png)

**Comment by eyalroz** [comment]
Hmm. Yes, you're right. Need to figure out how separate regular and dark theme icons.

**Comment by eyalroz** [comment]
Please try this build:

[bidimailui_0.13.1b1_tbird.zip](https://github.com/eyalroz/bidimailui/files/11215284/bidimailui_0.13.1b1_tbird.zip)

and let me know how it looks to you.

**Comment by yoav-steinberg** [comment]
much better!
![image](https://user-images.githubusercontent.com/1160578/231865627-78a65137-aead-4f76-ab10-88470bd5265b.png)

**Comment by yoav-steinberg** [comment]
:smile:
