### ISSUE TITLE
Question: Does it work with TB 102

### ISSUE THREAD

**Issue by MehdiChinoune** [eyalroz/bidimailui#59]

**Comment by eyalroz** [comment]
Sort of, but apparently there are issues. I will try to address them in the coming weeks. Please remind me if I haven't posted here within 2 weeks or so.

**Comment by eyalroz** [comment]
Please try the new beta release:

https://github.com/eyalroz/bidimailui/releases/tag/v0.13b1

**Comment by MehdiChinoune** [comment]
> Please try the new beta release:
> 
> https://github.com/eyalroz/bidimailui/releases/tag/v0.13b1

I have to upgrade TB first.
