### ISSUE TITLE
Thunderbird 115 support

### ISSUE THREAD

**Issue by orennahum** [eyalroz/bidimailui#67]
The new version of TB is about to be released in a month or so. When are you going to release a compatible version of the addon?

Thanks,
Oren

**Comment by Ashdemai** [comment]
Any update on whether this extension going to be compatible with the new version now that it's released?

**Comment by eyalroz** [comment]
I've been focusing on removedupes so far. I haven't been able to get even that done - can't get buttons to appear; and there are some dialog size imperfection - but I think I ought to get started here as well.

**Comment by eyalroz** [comment]
This is now a milestone rather than a bug, and work has resumed.

**Comment by eyalroz** [comment]
Please try out [the new beta](https://github.com/eyalroz/bidimailui/releases/tag/v0.14.0-b1) and open a new issue if you experience any problems.
